from village.config._agents import AgentConfig, _parse_ppc_traits, _validate_acp_agent
from village.config._agents_yaml import AgentRole, AgentsYamlConfig, load_agents_yaml, load_agents_yaml_from_string
from village.config._helpers import _env_or_config, _parse_bool, _parse_int, _parse_str
from village.config._loader import (
    Config,
    GlobalConfig,
    _build_config,
    _build_sub_configs,
    _global_config_path,
    _load_global_config,
    _merge_configs,
    _normalize_config,
    _parse_config_file,
    get_config,
    get_config_for_cwd,
    get_global_config,
)
from village.config._sub_configs import (
    ACPAgentCapability,
    ACPConfig,
    ApprovalConfig,
    CIConfig,
    ConflictConfig,
    CouncilConfig,
    DashboardConfig,
    DebugConfig,
    ExtensionConfig,
    LLMConfig,
    MCPConfig,
    MemoryConfig,
    MetricsConfig,
    NotificationConfig,
    OnboardConfig,
    SafetyConfig,
    TaskBreakdownConfig,
    TelegramConfig,
    TransportConfig,
)

DEFAULT_AGENT = "worker"
DEFAULT_MAX_WORKERS = 2
DEFAULT_QUEUE_TTL_MINUTES = 5
DEFAULT_SCM_KIND = "git"
DEFAULT_WORKTREES_DIR_NAME = ".worktrees"
TMUX_SESSION = "village"

__all__ = [
    "ACPAgentCapability",
    "ACPConfig",
    "AgentConfig",
    "AgentRole",
    "AgentsYamlConfig",
    "ApprovalConfig",
    "CIConfig",
    "Config",
    "ConflictConfig",
    "CouncilConfig",
    "DashboardConfig",
    "DebugConfig",
    "DEFAULT_AGENT",
    "DEFAULT_MAX_WORKERS",
    "DEFAULT_QUEUE_TTL_MINUTES",
    "DEFAULT_SCM_KIND",
    "DEFAULT_WORKTREES_DIR_NAME",
    "ExtensionConfig",
    "GlobalConfig",
    "LLMConfig",
    "MCPConfig",
    "MemoryConfig",
    "MetricsConfig",
    "NotificationConfig",
    "OnboardConfig",
    "SafetyConfig",
    "TaskBreakdownConfig",
    "TMUX_SESSION",
    "TelegramConfig",
    "TransportConfig",
    "_build_config",
    "_build_sub_configs",
    "_env_or_config",
    "_global_config_path",
    "_load_global_config",
    "_merge_configs",
    "_normalize_config",
    "_parse_bool",
    "_parse_config_file",
    "_parse_int",
    "_parse_ppc_traits",
    "_parse_str",
    "_validate_acp_agent",
    "get_config",
    "get_config_for_cwd",
    "get_global_config",
    "load_agents_yaml",
    "load_agents_yaml_from_string",
]
